/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 *
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem002 {
    public static int solution2(int n)
    {
        int a = 1;
        int b = 2;

        int fib_sum = 0;

        while(a <= n)
        {
            if(a % 2 == 0)
                fib_sum += a;

            int c = a + b;
            a = b;
            b = c;
        }

        return fib_sum;
    }

    public static void main(String args[])
    {
        System.out.println("The sum of the even valued terms in the fibonacci sequence is: " + solution2(4000000));
    }
}
